set(_CATKIN_CURRENT_PACKAGE "camera_tutorial")
set(camera_tutorial_VERSION "0.0.0")
set(camera_tutorial_MAINTAINER "jeongwoooh <jeongwoooh@todo.todo>")
set(camera_tutorial_PACKAGE_FORMAT "2")
set(camera_tutorial_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(camera_tutorial_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(camera_tutorial_BUILDTOOL_DEPENDS "catkin")
set(camera_tutorial_BUILDTOOL_EXPORT_DEPENDS )
set(camera_tutorial_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(camera_tutorial_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(camera_tutorial_TEST_DEPENDS )
set(camera_tutorial_DOC_DEPENDS )
set(camera_tutorial_URL_WEBSITE "")
set(camera_tutorial_URL_BUGTRACKER "")
set(camera_tutorial_URL_REPOSITORY "")
set(camera_tutorial_DEPRECATED "")