#!/usr/bin/env python
import rospy
import pcl
from sensor_msgs.msg import PointCloud2
from sensor_msgs.msg import PointCloud
import sensor_msgs.point_cloud2 as point_cloud2
import ros_numpy

def callback(data):
	pc = ros_numpy.numpify(data)
	points = np.zeros((pc.shape[0],3))
	points[:,0] = pc['x']
	points[:,1] = pc['y']
	points[:,2] = pc['z']
	p = pcl.PointCloud(np.array(points, dtype=np.float32))

rospy.init_node('listener', anonymous = True)
rospy.Subscriber("/camera/depth/points", PointCloud2, callback)
Point_pub = rospy.Publisher("/pointcloud", PointCloud)
Point_pub.publish(p)
rospy.spin()